### ISSUE TITLE
課題_0717

### ISSUE THREAD

**Issue by technicakidz** [dsuke0526/my-first-blog#12]
### 概要
やることを記載する．
残った部分は課題にする．

### TODO
以下は一つの宿題に対して1つのブランチを作成してください．
また，プルリクエストをだしてレビュー依頼してください．

- [x] [宿題: ウェブサイトにもっと機能を追加しよう!](https://tutorial-extensions.djangogirls.org/ja/homework) 
- [x] [宿題: ウェブサイトをセキュアにする](https://tutorial-extensions.djangogirls.org/ja/authentication_authorization)
- [x] [宿題:コメントモデルを作ろう](https://tutorial-extensions.djangogirls.org/ja/homework_create_more_models)
- [x] [PostgreSQLのインストール](https://tutorial-extensions.djangogirls.org/ja/optional_postgresql_installation#postgresqlnoinsutru)
- [x] README を追加するPRを作成，マージまでしてもらう

**Comment by technicakidz** [comment]
[PostgreSQLのインストール](https://tutorial-extensions.djangogirls.org/ja/optional_postgresql_installation#postgresqlnoinsutru)
上記を進める際にEDBのサインアップがうまくいかなかった．代替案を考える．

**Comment by technicakidz** [comment]
レッスン内で解決しましたので，issue をクローズします．
