### ISSUE TITLE
課題_220806

### ISSUE THREAD

**Issue by technicakidz** [dsuke0526/my-first-blog#21]
### TODO
「オリジナルアプリのゴールを明確にする作業」
- [x] 現状の機能を洗い出す，wikiにまとめる(優先度高)
- [x] README の内容を修正するためのブランチを作成
- [x] ↑PR作成し，https://github.com/technicakidz/djangogirls_pure を参考に体裁と内容を整える
- [x] オリジナル機能のアイデアをこの issue のコメントに列挙
- [ ] それぞれの実現に必要なライブラリやツールを調査
- [ ] レイアウトを [Figma](https://www.figma.com/ja/) 等で作成(使い方は調べてもらう)

**Comment by dsuke0526** [comment]
# 機能
* 各種ログイン機能(Google,,Facebook等)
* いいね機能
ユーザーの投稿,作品に対して
* おすすめの漫画をレコメンド機能
* サーチ機能
* コメント機能
* 漫画の発売日通知機能

**Comment by technicakidz** [comment]
wiki にアイデアでだしたオリジナル機能の洗い出しが完了したのでクローズします．
