### ISSUE TITLE
課題_220821

### ISSUE THREAD

**Issue by technicakidz** [dsuke0526/my-first-blog#22]
### TODO
「オリジナルアプリのゴールを明確にする作業」
- [x] 機能一覧 wiki の完成
- [x] アプリ基本設計 wiki の完成
- [x] オリジナル機能 https://github.com/dsuke0526/my-first-blog/issues/21#issuecomment-1221226430 の実装要件を wiki に追記
- [x] ポートフォリオサイトの製作
- github 経由でネットに公開する方法 https://developer.mozilla.org/ja/docs/Learn/Getting_started_with_the_web/Publishing_your_website#publishing_via_github
#### 前回繰越し分
(オリジナル機能)
- [ ] それぞれの実現に必要なライブラリやツールを調査
- [x] #23
- adobe XD でも可能．こちらは教材あり([AdobeXDでWebサイトのデザインを作ろう](https://www.sejuku.net/plus/programs/30/chapters))．
-  [Figma](https://www.figma.com/ja/)

**Comment by dsuke0526** [comment]
readme.mdがindex.htmlより優先されて表示されるのですがどうすればいいですか？

**Comment by technicakidz** [comment]
readmeがどうしても優先されそうな場合は、portfolio/ 配下のファイルをルートに置くようにしてみるといかがでしょうか？

**Comment by technicakidz** [comment]
無事 github pages でデプロイ完了したことを確認できたのでクローズします．
